name: build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.69
          target: x86_64-unknown-linux-musl
      - run: cargo test
      - run: cargo build --release --target=x86_64-unknown-linux-musl
