name: build

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends musl-tools
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.69
          target: x86_64-unknown-linux-musl
          override: true
      - run: cargo test
      - run: cargo build --release --target=x86_64-unknown-linux-musl
